name: jekyll
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - autoconf=2.71
  - automake=1.17
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cmake=3.30.3
  - gcc=14.1.0
  - gcc_impl_linux-64=14.1.0
  - gcc_linux-64=14.1.0
  - gdbm=1.18
  - gmp=6.3.0
  - gxx_impl_linux-64=14.1.0
  - gxx_linux-64=14.1.0
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libcurl=8.9.1
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnghttp2=1.58.0
  - libsanitizer=14.1.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=14.1.0
  - libstdcxx-ng=14.1.0
  - libuv=1.48.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - m4=1.4.18
  - make=4.4.1
  - ncurses=6.5
  - openssl=3.3.2
  - perl=5.32.1
  - readline=8.2
  - rhash=1.4.4
  - ruby=3.3.3
  - sysroot_linux-64=2.17
  - tzdata=2024a
  - xz=5.2.6
  - yaml=0.2.5
  - zstd=1.5.6
